-- 🚨 SCRIPT DE EMERGÊNCIA V2: DESABILITAR RLS GERAL (OPÇÃO 1)
-- MOTIVO: ERR_CONNECTION_RESET persistente. Bloqueio total de RLS suspeito.
-- AÇÃO: Desativa RLS em TODAS as tabelas do sistema para garantir o carregamento.

-- Tabelas Core
ALTER TABLE patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE professionals DISABLE ROW LEVEL SECURITY;
ALTER TABLE clinics DISABLE ROW LEVEL SECURITY;

-- Tabelas Financeiras
ALTER TABLE clinic_financial_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_registers DISABLE ROW LEVEL SECURITY;
ALTER TABLE price_tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE price_table_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE financial_installments DISABLE ROW LEVEL SECURITY;
ALTER TABLE budgets DISABLE ROW LEVEL SECURITY;

-- Tabelas Clínicas/Operacionais
ALTER TABLE procedure DISABLE ROW LEVEL SECURITY;
ALTER TABLE appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE treatment_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_templates DISABLE ROW LEVEL SECURITY;

-- Tabelas CRM/Intel
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights DISABLE ROW LEVEL SECURITY;

-- Garante permissões (Just in case)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_role;

SELECT '🚨 RLS DESATIVADO EM TUDO. Modo Desenvolvimento Liberado.' as status;
