-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  icon text,
  category text,
  xp_reward integer DEFAULT 0,
  rarity text DEFAULT 'common'::text CHECK (rarity = ANY (ARRAY['common'::text, 'rare'::text, 'epic'::text, 'legendary'::text])),
  requirements jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_insights (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  category text NOT NULL,
  title text NOT NULL,
  explanation text,
  priority text CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'critico'::text])),
  action_label text,
  action_type text,
  related_entity_id uuid,
  status text DEFAULT 'open'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_insights_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  key_hash text NOT NULL,
  prefix text NOT NULL,
  scopes ARRAY DEFAULT ARRAY['read_only'::text],
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.appointment_confirmations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL UNIQUE,
  clinic_id uuid NOT NULL,
  reminder_sent_at timestamp with time zone,
  reminder_channel text CHECK (reminder_channel = ANY (ARRAY['WHATSAPP'::text, 'SMS'::text, 'EMAIL'::text, 'PHONE'::text])),
  reminder_message text,
  confirmation_status text DEFAULT 'PENDING'::text CHECK (confirmation_status = ANY (ARRAY['PENDING'::text, 'CONFIRMED'::text, 'CANCELLED'::text, 'RESCHEDULED'::text, 'NO_RESPONSE'::text])),
  confirmed_at timestamp with time zone,
  confirmed_by text,
  confirmation_method text CHECK (confirmation_method = ANY (ARRAY['WHATSAPP'::text, 'SMS'::text, 'EMAIL'::text, 'PHONE'::text, 'IN_PERSON'::text])),
  rescheduled_to uuid,
  cancellation_reason text,
  cancellation_notes text,
  auto_reminder_24h_sent boolean DEFAULT false,
  auto_reminder_24h_sent_at timestamp with time zone,
  auto_reminder_2h_sent boolean DEFAULT false,
  auto_reminder_2h_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointment_confirmations_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_confirmations_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT appointment_confirmations_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT appointment_confirmations_rescheduled_to_fkey FOREIGN KEY (rescheduled_to) REFERENCES public.appointments(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  date timestamp with time zone NOT NULL,
  duration integer NOT NULL,
  type USER-DEFINED DEFAULT 'EVALUATION'::appointment_type,
  status USER-DEFINED DEFAULT 'PENDING'::appointment_status,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  bank_name text NOT NULL,
  account_number text,
  agency text,
  name text NOT NULL,
  initial_balance numeric DEFAULT 0,
  current_balance numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid,
  date date NOT NULL,
  amount numeric NOT NULL,
  description text,
  doc_number text,
  is_reconciled boolean DEFAULT false,
  matched_transaction_id uuid,
  import_batch_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_transactions_matched_transaction_id_fkey FOREIGN KEY (matched_transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.budget_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  budget_id uuid NOT NULL,
  procedure_id uuid,
  procedure_name text NOT NULL,
  region text,
  quantity integer DEFAULT 1,
  unit_value numeric NOT NULL,
  total_value numeric NOT NULL,
  amount_paid numeric,
  payment_date date,
  payment_method text,
  payment_notes text,
  face text,
  tooth_number integer,
  CONSTRAINT budget_items_pkey PRIMARY KEY (id),
  CONSTRAINT budget_items_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT budget_items_procedure_id_fkey FOREIGN KEY (procedure_id) REFERENCES public.procedure(id)
);
CREATE TABLE public.budget_negotiation_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  budget_id uuid,
  previous_status text,
  new_status text,
  notes text,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_negotiation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT budget_negotiation_logs_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT budget_negotiation_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.budget_payment_simulations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  budget_id uuid,
  label text,
  total_value numeric,
  down_payment numeric,
  installments integer,
  installment_value numeric,
  is_selected boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_payment_simulations_pkey PRIMARY KEY (id),
  CONSTRAINT budget_payment_simulations_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id)
);
CREATE TABLE public.budgets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  patient_id uuid NOT NULL,
  doctor_id uuid,
  price_table_id uuid,
  status USER-DEFINED DEFAULT 'DRAFT'::budget_status,
  total_value numeric NOT NULL,
  discount numeric DEFAULT 0,
  final_value numeric NOT NULL,
  payment_config jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clinic_id uuid,
  rejection_reason text,
  lost_at timestamp with time zone,
  potential_margin numeric,
  expires_at timestamp with time zone,
  option_group_id uuid,
  option_label text,
  last_follow_up_at timestamp with time zone,
  follow_up_count integer DEFAULT 0,
  discount_type text DEFAULT 'PERCENTAGE'::text,
  discount_value numeric DEFAULT 0,
  down_payment_value numeric DEFAULT 0,
  installments_count integer DEFAULT 1,
  payment_method_id uuid,
  sales_rep_id uuid,
  CONSTRAINT budgets_pkey PRIMARY KEY (id),
  CONSTRAINT budgets_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT budgets_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT budgets_price_table_id_fkey FOREIGN KEY (price_table_id) REFERENCES public.price_tables(id),
  CONSTRAINT budgets_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT budgets_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES public.users(id)
);
CREATE TABLE public.business_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  title text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['REVENUE'::text, 'PATIENTS'::text, 'PROCEDURES'::text, 'CONVERSION'::text])),
  target_value numeric NOT NULL,
  current_value numeric DEFAULT 0,
  deadline date NOT NULL,
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'COMPLETED'::text, 'CANCELLED'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_goals_pkey PRIMARY KEY (id),
  CONSTRAINT business_goals_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.cash_registers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  user_id uuid NOT NULL,
  opened_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  opening_balance numeric NOT NULL,
  closing_balance numeric,
  calculated_balance numeric NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['OPEN'::text, 'CLOSED'::text, 'AUDIT_PENDING'::text])),
  observations text,
  declared_balance numeric,
  difference_amount numeric,
  difference_reason text,
  CONSTRAINT cash_registers_pkey PRIMARY KEY (id),
  CONSTRAINT cash_registers_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT cash_registers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  type text CHECK (type = ANY (ARRAY['ASSET'::text, 'LIABILITY'::text, 'EQUITY'::text, 'REVENUE'::text, 'EXPENSE'::text])),
  parent_id uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT chart_of_accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.clinic_capacity_config (
  clinic_id uuid NOT NULL,
  active_chairs integer DEFAULT 1,
  weekly_hours integer DEFAULT 40,
  efficiency_rate numeric DEFAULT 0.80,
  total_monthly_hours numeric DEFAULT ((((weekly_hours * 4) * active_chairs))::numeric * efficiency_rate),
  last_updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_capacity_config_pkey PRIMARY KEY (clinic_id),
  CONSTRAINT clinic_capacity_config_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_cost_structure (
  clinic_id uuid NOT NULL,
  fixed_costs_monthly numeric NOT NULL DEFAULT 0,
  desired_prolabore numeric NOT NULL DEFAULT 0,
  productive_chairs integer DEFAULT 1,
  weekly_hours integer DEFAULT 40,
  cost_per_minute numeric DEFAULT 
CASE
    WHEN ((((productive_chairs * weekly_hours) * 4) * 60) > 0) THEN ((fixed_costs_monthly + desired_prolabore) / ((((productive_chairs * weekly_hours) * 4) * 60))::numeric)
    ELSE (0)::numeric
END,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  efficiency_rate numeric DEFAULT 0.80,
  available_minutes_month integer DEFAULT 0,
  CONSTRAINT clinic_cost_structure_pkey PRIMARY KEY (clinic_id),
  CONSTRAINT clinic_cost_structure_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_financial_settings (
  clinic_id uuid NOT NULL,
  force_cash_opening boolean DEFAULT true,
  force_daily_closing boolean DEFAULT true,
  allow_negative_balance boolean DEFAULT false,
  blind_closing boolean DEFAULT true,
  default_change_fund numeric DEFAULT 100.00,
  max_difference_without_approval numeric DEFAULT 50.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_financial_settings_pkey PRIMARY KEY (clinic_id),
  CONSTRAINT clinic_financial_settings_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_kpis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_revenue numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  net_profit numeric DEFAULT 0,
  new_patients_count integer DEFAULT 0,
  returning_patients_count integer DEFAULT 0,
  lost_patients_count integer DEFAULT 0,
  budgets_created_count integer DEFAULT 0,
  budgets_approved_count integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  appointments_scheduled integer DEFAULT 0,
  appointments_completed integer DEFAULT 0,
  no_show_rate numeric DEFAULT 0,
  average_budget_value numeric DEFAULT 0,
  average_treatment_value numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_kpis_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_kpis_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_landing_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  slug text UNIQUE,
  page_title text,
  bio_text text,
  primary_color text,
  profile_photo_url text,
  cover_photo_url text,
  show_reviews boolean DEFAULT true,
  show_map boolean DEFAULT true,
  allow_online_scheduling boolean DEFAULT true,
  whatsapp_link text,
  instagram_link text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_landing_pages_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_landing_pages_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinical_form_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  template_id uuid,
  patient_id uuid,
  responses jsonb NOT NULL DEFAULT '{}'::jsonb,
  filled_by uuid,
  filled_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_signature_url text,
  professional_signature_url text,
  CONSTRAINT clinical_form_responses_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_form_responses_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinical_form_responses_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.clinical_form_templates(id),
  CONSTRAINT clinical_form_responses_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_form_responses_filled_by_fkey FOREIGN KEY (filled_by) REFERENCES public.users(id)
);
CREATE TABLE public.clinical_form_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  description text,
  category text DEFAULT 'ANAMNESIS'::text CHECK (category = ANY (ARRAY['ANAMNESIS'::text, 'CONSENT'::text, 'EVALUATION'::text, 'FOLLOW_UP'::text, 'OTHER'::text])),
  fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  required_for_first_appointment boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinical_form_templates_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_form_templates_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinical_form_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.clinical_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  image_type text NOT NULL CHECK (image_type = ANY (ARRAY['XRAY_PERIAPICAL'::text, 'XRAY_PANORAMIC'::text, 'XRAY_BITEWING'::text, 'CBCT'::text, 'INTRAORAL_PHOTO'::text, 'EXTRAORAL_PHOTO'::text, 'SMILE_PHOTO'::text, 'SCAN_3D'::text, 'OTHER'::text])),
  file_url text NOT NULL,
  thumbnail_url text,
  file_size_kb integer,
  tooth_number integer,
  region text,
  capture_date timestamp with time zone DEFAULT now(),
  notes text,
  tags ARRAY,
  treatment_item_id uuid,
  budget_id uuid,
  is_before_treatment boolean DEFAULT true,
  is_public boolean DEFAULT false,
  patient_consent_signed boolean DEFAULT false,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinical_images_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_images_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_images_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinical_images_treatment_item_id_fkey FOREIGN KEY (treatment_item_id) REFERENCES public.treatment_items(id),
  CONSTRAINT clinical_images_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT clinical_images_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.clinical_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  type text NOT NULL,
  content text NOT NULL,
  date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinical_notes_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_notes_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_notes_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.clinics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  cnpj text,
  address text,
  phone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  code text NOT NULL,
  opening_time time without time zone,
  closing_time time without time zone,
  slot_duration integer DEFAULT 30,
  working_days ARRAY DEFAULT ARRAY['monday'::text, 'tuesday'::text, 'wednesday'::text, 'thursday'::text, 'friday'::text],
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text])),
  logo_light_url text,
  logo_dark_url text,
  favicon_url text,
  primary_color character varying DEFAULT '#3B82F6'::character varying,
  secondary_color character varying DEFAULT '#10B981'::character varying,
  document_footer text DEFAULT '{{CLINIC_NAME}} - CNPJ: {{CNPJ}}
{{ADDRESS}} - Tel: {{PHONE}}
Responsável Técnico: {{RT_NAME}} - {{CRO}}'::text,
  auto_logout_minutes integer DEFAULT 30,
  require_password_on_unlock boolean DEFAULT true,
  enable_audit_log boolean DEFAULT true,
  max_failed_login_attempts integer DEFAULT 5,
  lockout_duration_minutes integer DEFAULT 15,
  block_debtors_scheduling boolean DEFAULT false,
  debtor_block_days integer DEFAULT 30,
  debtor_warning_message text DEFAULT 'Paciente possui débitos em atraso. Regularize os pagamentos antes de agendar.'::text,
  max_discount_without_approval numeric DEFAULT 5.00,
  require_manager_password_for_discount boolean DEFAULT true,
  discount_approval_message text DEFAULT 'Desconto acima do limite permitido. Solicite aprovação do gestor.'::text,
  backup_frequency text DEFAULT 'WEEKLY'::text CHECK (backup_frequency = ANY (ARRAY['DAILY'::text, 'WEEKLY'::text, 'MONTHLY'::text, 'NEVER'::text])),
  backup_email text,
  last_backup_at timestamp with time zone,
  goals jsonb DEFAULT '{"new_patients": 20, "no_show_rate": 5, "average_ticket": 2000, "occupancy_rate": 80, "conversion_rate": 30, "monthly_revenue": 50000, "monthly_net_result": 25000}'::jsonb,
  type USER-DEFINED DEFAULT 'PRODUCTION'::clinic_type,
  tax_rate_percent numeric DEFAULT 0,
  commission_calculation_base text DEFAULT 'NET_RECEIPT'::text CHECK (commission_calculation_base = ANY (ARRAY['GROSS_SALE'::text, 'NET_RECEIPT'::text])),
  CONSTRAINT clinics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.commission_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  professional_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_procedures_value numeric DEFAULT 0,
  commission_value numeric DEFAULT 0,
  procedures_count integer DEFAULT 0,
  details jsonb,
  status text DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'PAID'::text, 'CANCELLED'::text])),
  paid_at timestamp with time zone,
  paid_by uuid,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_type text DEFAULT 'PROFESSIONAL'::text CHECK (user_type = ANY (ARRAY['PROFESSIONAL'::text, 'SALES_REP'::text])),
  CONSTRAINT commission_payments_pkey PRIMARY KEY (id),
  CONSTRAINT commission_payments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT commission_payments_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT commission_payments_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(id)
);
CREATE TABLE public.conventions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  code text,
  price_table_id uuid,
  status text NOT NULL DEFAULT 'Ativo'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conventions_pkey PRIMARY KEY (id),
  CONSTRAINT conventions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT conventions_price_table_id_fkey FOREIGN KEY (price_table_id) REFERENCES public.price_tables(id)
);
CREATE TABLE public.cost_centers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  code text,
  is_active boolean DEFAULT true,
  CONSTRAINT cost_centers_pkey PRIMARY KEY (id),
  CONSTRAINT cost_centers_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.custom_lead_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  status_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_lead_status_pkey PRIMARY KEY (id),
  CONSTRAINT custom_lead_status_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.dental_charting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  tooth_number integer NOT NULL CHECK (tooth_number >= 11 AND tooth_number <= 85),
  status_code text CHECK (status_code = ANY (ARRAY['SOUND'::text, 'DECAYED'::text, 'FILLED'::text, 'MISSING'::text, 'IMPLANT'::text, 'CROWN'::text, 'VENEER'::text, 'ENDODONTIC'::text, 'FRACTURED'::text, 'EXTRACTED'::text])),
  surfaces jsonb,
  existing_material text,
  condition_notes text,
  last_update timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT dental_charting_pkey PRIMARY KEY (id),
  CONSTRAINT dental_charting_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT dental_charting_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.document_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['PRESCRIPTION'::text, 'CERTIFICATE'::text, 'DECLARATION'::text, 'TREATMENT_PLAN'::text, 'BUDGET'::text, 'OTHER'::text])),
  content text NOT NULL,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_templates_pkey PRIMARY KEY (id),
  CONSTRAINT document_templates_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT document_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.expense_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_variable_cost boolean DEFAULT false,
  CONSTRAINT expense_category_pkey PRIMARY KEY (id),
  CONSTRAINT expense_category_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  provider text,
  amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  due_date date NOT NULL,
  status USER-DEFINED DEFAULT 'PENDING'::payment_status,
  created_at timestamp with time zone DEFAULT now(),
  payment_date date,
  payment_method text,
  payment_notes text,
  supplier_id uuid,
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT expenses_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.financial_installments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  description text NOT NULL,
  due_date date NOT NULL,
  amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  status USER-DEFINED DEFAULT 'PENDING'::payment_status,
  payment_method text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT financial_installments_pkey PRIMARY KEY (id),
  CONSTRAINT financial_installments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT financial_installments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.fiscal_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  transaction_id uuid,
  patient_id uuid,
  rps_number integer,
  invoice_number integer,
  issue_date timestamp with time zone DEFAULT now(),
  verification_code text,
  service_code text,
  value numeric NOT NULL,
  iss_value numeric DEFAULT 0,
  xml_url text,
  pdf_url text,
  status text DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'ISSUED'::text, 'CANCELLED'::text, 'ERROR'::text])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fiscal_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT fiscal_invoices_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT fiscal_invoices_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT fiscal_invoices_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.fixed_cost_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  category text CHECK (category = ANY (ARRAY['ADMINISTRATIVE'::text, 'STAFF'::text, 'INFRASTRUCTURE'::text, 'MARKETING'::text, 'PROLABORE'::text, 'OTHER'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fixed_cost_items_pkey PRIMARY KEY (id),
  CONSTRAINT fixed_cost_items_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.gamification_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL UNIQUE,
  xp_appointment_completed integer DEFAULT 10,
  xp_budget_approved integer DEFAULT 50,
  xp_patient_referral integer DEFAULT 100,
  xp_review_received integer DEFAULT 25,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gamification_rules_pkey PRIMARY KEY (id),
  CONSTRAINT gamification_rules_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.health_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  event_type text NOT NULL,
  impact integer NOT NULL,
  pillar text CHECK (pillar = ANY (ARRAY['marketing'::text, 'sales'::text, 'clinical'::text, 'operational'::text, 'financial'::text, 'overall'::text])),
  title text,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT health_events_pkey PRIMARY KEY (id),
  CONSTRAINT health_events_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.installments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  budget_id uuid,
  installment_number integer NOT NULL,
  total_installments integer NOT NULL,
  amount numeric NOT NULL,
  due_date date NOT NULL,
  paid_date date,
  status text NOT NULL DEFAULT 'PENDING'::text,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT installments_pkey PRIMARY KEY (id),
  CONSTRAINT installments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT installments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT installments_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id)
);
CREATE TABLE public.insurance_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  price_table_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  active boolean DEFAULT true,
  CONSTRAINT insurance_plans_pkey PRIMARY KEY (id),
  CONSTRAINT insurance_plans_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT insurance_plans_price_table_id_fkey FOREIGN KEY (price_table_id) REFERENCES public.price_tables(id)
);
CREATE TABLE public.integration_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  integration_type text CHECK (integration_type = ANY (ARRAY['WEBHOOK'::text, 'API'::text, 'BACKUP'::text])),
  status text CHECK (status = ANY (ARRAY['SUCCESS'::text, 'FAILURE'::text])),
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integration_logs_pkey PRIMARY KEY (id),
  CONSTRAINT integration_logs_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.inventory_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_categories_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_categories_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  category_id uuid,
  name text NOT NULL,
  description text,
  sku text,
  barcode text,
  unit_of_measure text DEFAULT 'UNIT'::text CHECK (unit_of_measure = ANY (ARRAY['UNIT'::text, 'BOX'::text, 'KG'::text, 'G'::text, 'ML'::text, 'L'::text, 'METER'::text, 'OTHER'::text])),
  current_stock numeric DEFAULT 0 CHECK (current_stock >= 0::numeric),
  minimum_stock numeric DEFAULT 0,
  maximum_stock numeric,
  unit_cost numeric DEFAULT 0,
  selling_price numeric DEFAULT 0,
  supplier_name text,
  supplier_contact text,
  is_active boolean DEFAULT true,
  requires_prescription boolean DEFAULT false,
  is_controlled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT inventory_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.inventory_categories(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['IN'::text, 'OUT'::text, 'ADJUSTMENT'::text, 'TRANSFER'::text, 'LOSS'::text, 'RETURN'::text])),
  quantity numeric NOT NULL,
  unit_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0,
  reference_type text CHECK (reference_type = ANY (ARRAY['PURCHASE'::text, 'SALE'::text, 'PROCEDURE'::text, 'ADJUSTMENT'::text, 'OTHER'::text])),
  reference_id uuid,
  reason text,
  notes text,
  stock_before numeric,
  stock_after numeric,
  performed_by uuid,
  performed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT inventory_movements_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id),
  CONSTRAINT inventory_movements_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.users(id)
);
CREATE TABLE public.lab_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  supplier_name text NOT NULL,
  supplier_contact text,
  supplier_email text,
  supplier_phone text,
  treatment_item_id uuid,
  budget_id uuid,
  work_description text NOT NULL,
  work_type text CHECK (work_type = ANY (ARRAY['CROWN'::text, 'BRIDGE'::text, 'DENTURE'::text, 'IMPLANT'::text, 'VENEER'::text, 'ORTHODONTIC'::text, 'OTHER'::text])),
  quantity integer DEFAULT 1,
  sent_date date NOT NULL,
  expected_return_date date NOT NULL,
  received_date date,
  delivered_to_patient_date date,
  cost numeric DEFAULT 0,
  is_paid boolean DEFAULT false,
  payment_date date,
  payment_method text,
  status text DEFAULT 'PREPARING'::text CHECK (status = ANY (ARRAY['PREPARING'::text, 'SENT'::text, 'IN_PROGRESS'::text, 'READY'::text, 'RECEIVED'::text, 'DELIVERED_TO_PATIENT'::text, 'RETURNED_FOR_CORRECTION'::text, 'CANCELLED'::text])),
  shade_guide text,
  material text,
  special_instructions text,
  quality_check_passed boolean,
  quality_notes text,
  returned_for_correction_count integer DEFAULT 0,
  correction_reason text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_orders_pkey PRIMARY KEY (id),
  CONSTRAINT lab_orders_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT lab_orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT lab_orders_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT lab_orders_treatment_item_id_fkey FOREIGN KEY (treatment_item_id) REFERENCES public.treatment_items(id),
  CONSTRAINT lab_orders_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT lab_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.lead_interactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  user_id uuid NOT NULL,
  type text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT lead_interactions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lead_source (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_source_pkey PRIMARY KEY (id),
  CONSTRAINT lead_source_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.lead_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  title text NOT NULL,
  due_date date NOT NULL,
  completed boolean DEFAULT false,
  CONSTRAINT lead_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT lead_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  source text NOT NULL,
  status USER-DEFINED DEFAULT 'NEW'::lead_status,
  interest text,
  value numeric,
  patient_id uuid,
  budget_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_interaction timestamp with time zone DEFAULT now(),
  campaign_id uuid,
  lead_score integer DEFAULT 0,
  priority text DEFAULT 'MEDIUM'::text CHECK (priority = ANY (ARRAY['HIGH'::text, 'MEDIUM'::text, 'LOW'::text])),
  desired_treatment text,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT leads_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id)
);
CREATE TABLE public.marketing_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  channel text NOT NULL,
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'PAUSED'::text, 'COMPLETED'::text])),
  budget numeric DEFAULT 0,
  start_date date DEFAULT CURRENT_DATE,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_campaigns_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.medical_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['ALLERGY'::text, 'CONDITION'::text, 'MEDICATION'::text, 'RISK'::text, 'CONTRAINDICATION'::text])),
  description text NOT NULL,
  severity text DEFAULT 'MEDIUM'::text CHECK (severity = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'CRITICAL'::text])),
  is_critical boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medical_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT medical_alerts_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medical_alerts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.medical_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  certificate_type text CHECK (certificate_type = ANY (ARRAY['ABSENCE'::text, 'COMPANION'::text, 'FITNESS'::text, 'PROCEDURE'::text, 'OTHER'::text])),
  days_off integer,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text,
  cid_code text,
  content text NOT NULL,
  digital_signature_url text,
  signed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medical_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT medical_certificates_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medical_certificates_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT medical_certificates_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.medication_library (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  active_ingredient text,
  dosage text,
  form text CHECK (form = ANY (ARRAY['TABLET'::text, 'CAPSULE'::text, 'SYRUP'::text, 'OINTMENT'::text, 'INJECTION'::text, 'DROPS'::text, 'OTHER'::text])),
  is_controlled boolean DEFAULT false,
  requires_special_prescription boolean DEFAULT false,
  common_usage text,
  common_dosage_instructions text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medication_library_pkey PRIMARY KEY (id),
  CONSTRAINT medication_library_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.notification_channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  channel_type text NOT NULL CHECK (channel_type = ANY (ARRAY['WHATSAPP'::text, 'EMAIL'::text, 'SMS'::text])),
  provider_name text,
  api_key text,
  api_secret text,
  sender_id text,
  is_active boolean DEFAULT false,
  daily_limit integer DEFAULT 100,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_channels_pkey PRIMARY KEY (id),
  CONSTRAINT notification_channels_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  patient_id uuid,
  recipient_contact text NOT NULL,
  channel_type text NOT NULL,
  template_id uuid,
  content_sent text,
  status text DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'DELIVERED'::text, 'READ'::text, 'FAILED'::text])),
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT notification_logs_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT notification_logs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  trigger_event text NOT NULL CHECK (trigger_event = ANY (ARRAY['APPOINTMENT_CREATED'::text, 'APPOINTMENT_REMINDER'::text, 'APPOINTMENT_MISSED'::text, 'BIRTHDAY'::text, 'RECALL_6_MONTHS'::text, 'PAYMENT_DUE'::text, 'CUSTOM'::text])),
  channel_type text DEFAULT 'WHATSAPP'::text CHECK (channel_type = ANY (ARRAY['WHATSAPP'::text, 'EMAIL'::text, 'SMS'::text])),
  content text NOT NULL,
  schedule_offset_minutes integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.ortho_aligner_stock (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  treatment_plan_id uuid NOT NULL,
  aligner_number integer NOT NULL,
  arch text NOT NULL CHECK (arch = ANY (ARRAY['UPPER'::text, 'LOWER'::text])),
  status text DEFAULT 'ORDERED'::text CHECK (status = ANY (ARRAY['ORDERED'::text, 'RECEIVED'::text, 'DELIVERED'::text, 'IN_USE'::text, 'COMPLETED'::text, 'LOST'::text, 'DAMAGED'::text])),
  ordered_date date,
  received_date date,
  delivered_date date,
  expected_start_date date,
  actual_start_date date,
  expected_end_date date,
  actual_end_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ortho_aligner_stock_pkey PRIMARY KEY (id),
  CONSTRAINT ortho_aligner_stock_treatment_plan_id_fkey FOREIGN KEY (treatment_plan_id) REFERENCES public.ortho_treatment_plans(id)
);
CREATE TABLE public.ortho_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL,
  treatment_plan_id uuid NOT NULL,
  appointment_type text CHECK (appointment_type = ANY (ARRAY['INSTALLATION'::text, 'MAINTENANCE'::text, 'ADJUSTMENT'::text, 'EMERGENCY'::text, 'REMOVAL'::text, 'RETENTION_CHECK'::text])),
  archwire_upper text,
  elastics_upper text,
  chain_upper text,
  archwire_lower text,
  elastics_lower text,
  chain_lower text,
  aligners_delivered_from integer,
  aligners_delivered_to integer,
  aligners_stock_given integer,
  ipr_performed boolean DEFAULT false,
  ipr_teeth text,
  attachments_placed boolean DEFAULT false,
  attachments_removed boolean DEFAULT false,
  attachments_list text,
  bracket_broken ARRAY,
  bracket_replaced ARRAY,
  band_loose ARRAY,
  wire_broken boolean DEFAULT false,
  hygiene_score integer CHECK (hygiene_score >= 1 AND hygiene_score <= 5),
  compliance_score integer CHECK (compliance_score >= 1 AND compliance_score <= 5),
  cooperation_notes text,
  next_visit_plan text,
  next_visit_interval_days integer DEFAULT 30,
  extra_charge_reason text,
  extra_charge_value numeric DEFAULT 0,
  notes text,
  photos_urls ARRAY,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  current_aligner_upper integer,
  current_aligner_lower integer,
  CONSTRAINT ortho_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT ortho_appointments_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT ortho_appointments_treatment_plan_id_fkey FOREIGN KEY (treatment_plan_id) REFERENCES public.ortho_treatment_plans(id),
  CONSTRAINT ortho_appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ortho_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  budget_id uuid,
  professional_id uuid,
  contract_type text NOT NULL CHECK (contract_type = ANY (ARRAY['FIXED_BRACES'::text, 'ALIGNERS'::text, 'ORTHOPEDIC'::text, 'LINGUAL'::text, 'CERAMIC'::text])),
  total_value numeric NOT NULL CHECK (total_value > 0::numeric),
  down_payment numeric DEFAULT 0 CHECK (down_payment >= 0::numeric),
  monthly_payment numeric NOT NULL CHECK (monthly_payment > 0::numeric),
  number_of_months integer NOT NULL CHECK (number_of_months > 0),
  billing_day integer NOT NULL CHECK (billing_day >= 1 AND billing_day <= 31),
  start_date date NOT NULL,
  estimated_end_date date,
  actual_end_date date,
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'COMPLETED'::text, 'CANCELLED'::text])),
  suspension_reason text,
  suspended_at timestamp with time zone,
  auto_charge boolean DEFAULT false,
  block_scheduling_if_overdue boolean DEFAULT true,
  overdue_tolerance_days integer DEFAULT 10,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ortho_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT ortho_contracts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT ortho_contracts_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT ortho_contracts_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT ortho_contracts_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT ortho_contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ortho_treatment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  total_aligners_upper integer DEFAULT 0 CHECK (total_aligners_upper >= 0),
  total_aligners_lower integer DEFAULT 0 CHECK (total_aligners_lower >= 0),
  current_aligner_upper integer DEFAULT 0 CHECK (current_aligner_upper >= 0),
  current_aligner_lower integer DEFAULT 0 CHECK (current_aligner_lower >= 0),
  change_frequency_days integer DEFAULT 14 CHECK (change_frequency_days > 0),
  last_aligner_change_date date,
  next_aligner_change_date date,
  installation_date date,
  bracket_type text CHECK (bracket_type = ANY (ARRAY['METAL'::text, 'CERAMIC'::text, 'SAPPHIRE'::text, 'LINGUAL'::text, 'SELF_LIGATING'::text])),
  current_phase text DEFAULT 'DIAGNOSIS'::text CHECK (current_phase = ANY (ARRAY['DIAGNOSIS'::text, 'LEVELING'::text, 'ALIGNMENT'::text, 'WORKING'::text, 'SPACE_CLOSURE'::text, 'FINISHING'::text, 'RETENTION'::text])),
  phase_started_at date,
  treatment_goals text,
  extractions_planned ARRAY,
  extractions_completed ARRAY,
  ipr_planned jsonb DEFAULT '[]'::jsonb,
  attachments_planned ARRAY,
  attachments_placed ARRAY,
  notes text,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ortho_treatment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT ortho_treatment_plans_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.ortho_contracts(id),
  CONSTRAINT ortho_treatment_plans_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.patient_anamnesis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL UNIQUE,
  clinic_id uuid NOT NULL,
  has_allergies boolean DEFAULT false,
  allergies_list ARRAY,
  has_chronic_diseases boolean DEFAULT false,
  chronic_diseases ARRAY,
  current_medications ARRAY,
  previous_surgeries ARRAY,
  last_surgery_date date,
  is_pregnant boolean DEFAULT false,
  is_breastfeeding boolean DEFAULT false,
  has_pacemaker boolean DEFAULT false,
  has_bleeding_disorder boolean DEFAULT false,
  has_diabetes boolean DEFAULT false,
  has_hypertension boolean DEFAULT false,
  is_smoker boolean DEFAULT false,
  alcohol_consumption text CHECK (alcohol_consumption = ANY (ARRAY['NONE'::text, 'OCCASIONAL'::text, 'MODERATE'::text, 'HEAVY'::text])),
  last_dental_visit date,
  brushing_frequency integer DEFAULT 2,
  uses_floss boolean DEFAULT false,
  has_dental_sensitivity boolean DEFAULT false,
  previous_aesthetic_procedures ARRAY,
  aesthetic_goals text,
  filled_by uuid,
  filled_at timestamp with time zone DEFAULT now(),
  patient_signature_url text,
  patient_signature_date timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_anamnesis_pkey PRIMARY KEY (id),
  CONSTRAINT patient_anamnesis_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_anamnesis_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT patient_anamnesis_filled_by_fkey FOREIGN KEY (filled_by) REFERENCES public.users(id)
);
CREATE TABLE public.patient_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  patient_id uuid NOT NULL,
  template_id uuid,
  title text NOT NULL,
  type USER-DEFINED NOT NULL,
  content text NOT NULL,
  status text DEFAULT 'DRAFT'::text,
  created_at timestamp with time zone DEFAULT now(),
  signed_at timestamp with time zone,
  clinic_id uuid,
  print_status text DEFAULT 'PENDING'::text CHECK (print_status = ANY (ARRAY['PENDING'::text, 'PRINTED'::text, 'SIGNED'::text, 'ARCHIVED'::text])),
  generated_from_budget_id uuid,
  CONSTRAINT patient_documents_pkey PRIMARY KEY (id),
  CONSTRAINT patient_documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_documents_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT patient_documents_generated_from_budget_id_fkey FOREIGN KEY (generated_from_budget_id) REFERENCES public.budgets(id)
);
CREATE TABLE public.patient_recalls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  recall_type text NOT NULL CHECK (recall_type = ANY (ARRAY['PROPHYLAXIS'::text, 'PERIO'::text, 'BOTOX_RENEWAL'::text, 'FILLER_RENEWAL'::text, 'ORTHO_CHECK'::text, 'IMPLANT_MAINTENANCE'::text, 'CROWN_CHECK'::text, 'GENERAL_CHECKUP'::text, 'TREATMENT_CONTINUATION'::text, 'REACTIVATION'::text])),
  due_date date NOT NULL,
  created_date date DEFAULT CURRENT_DATE,
  status text DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'CONTACTED'::text, 'SCHEDULED'::text, 'OVERDUE'::text, 'LOST'::text, 'COMPLETED'::text])),
  linked_appointment_id uuid,
  original_treatment_id uuid,
  last_contact_date timestamp with time zone,
  contact_attempts integer DEFAULT 0,
  contact_method text CHECK (contact_method = ANY (ARRAY['WHATSAPP'::text, 'SMS'::text, 'EMAIL'::text, 'PHONE'::text, 'IN_PERSON'::text])),
  contact_notes text,
  priority integer DEFAULT 50 CHECK (priority >= 0 AND priority <= 100),
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_recalls_pkey PRIMARY KEY (id),
  CONSTRAINT patient_recalls_linked_appointment_id_fkey FOREIGN KEY (linked_appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT patient_recalls_original_treatment_id_fkey FOREIGN KEY (original_treatment_id) REFERENCES public.treatment_items(id),
  CONSTRAINT patient_recalls_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT patient_recalls_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT patient_recalls_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  cpf text,
  phone text NOT NULL,
  email text,
  birth_date date,
  gender text,
  address text,
  clinical_status text DEFAULT 'Em Tratamento'::text,
  total_approved numeric DEFAULT 0,
  total_paid numeric DEFAULT 0,
  balance_due numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  acquisition_source_id uuid,
  last_aesthetic_evaluation date,
  patient_ranking text DEFAULT 'STANDARD'::text,
  responsible_party_id uuid,
  relationship_type text CHECK (relationship_type = ANY (ARRAY['SELF'::text, 'PARENT'::text, 'SPOUSE'::text, 'GUARDIAN'::text, 'OTHER'::text])),
  profile_photo_url text,
  document_photo_front_url text,
  document_photo_back_url text,
  nickname text,
  occupation text,
  instagram_handle text,
  marital_status text CHECK (marital_status = ANY (ARRAY['SINGLE'::text, 'MARRIED'::text, 'DIVORCED'::text, 'WIDOWED'::text, 'OTHER'::text])),
  wedding_anniversary date,
  indication_patient_id uuid,
  vip_notes text,
  patient_score text DEFAULT 'STANDARD'::text CHECK (patient_score = ANY (ARRAY['DIAMOND'::text, 'GOLD'::text, 'STANDARD'::text, 'RISK'::text, 'BLACKLIST'::text])),
  bad_debtor boolean DEFAULT false,
  sentiment_status text DEFAULT 'NEUTRAL'::text CHECK (sentiment_status = ANY (ARRAY['VERY_HAPPY'::text, 'HAPPY'::text, 'NEUTRAL'::text, 'UNHAPPY'::text, 'COMPLAINING'::text])),
  photo_profile_url text,
  photo_smile_url text,
  photo_frontal_url text,
  photo_profile_side_url text,
  photo_document_front_url text,
  photo_document_back_url text,
  is_active boolean DEFAULT true,
  tags ARRAY DEFAULT '{}'::text[],
  zip_code text,
  street text,
  number text,
  complement text,
  neighborhood text,
  city text,
  state text,
  contact_preference text DEFAULT 'WHATSAPP'::text,
  origin text DEFAULT 'Instagram'::text,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT patients_acquisition_source_id_fkey FOREIGN KEY (acquisition_source_id) REFERENCES public.lead_source(id),
  CONSTRAINT patients_responsible_party_id_fkey FOREIGN KEY (responsible_party_id) REFERENCES public.patients(id),
  CONSTRAINT patients_indication_patient_id_fkey FOREIGN KEY (indication_patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.payment_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  installment_id uuid NOT NULL,
  amount numeric NOT NULL,
  date date NOT NULL,
  method text NOT NULL,
  notes text,
  transaction_id uuid UNIQUE,
  CONSTRAINT payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT payment_history_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES public.financial_installments(id),
  CONSTRAINT fk_payment_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.payment_method (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_method_pkey PRIMARY KEY (id),
  CONSTRAINT payment_method_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.payment_method_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  payment_method_name text NOT NULL,
  payment_type text DEFAULT 'CREDIT'::text CHECK (payment_type = ANY (ARRAY['CREDIT'::text, 'DEBIT'::text, 'PIX'::text, 'BOLETO'::text, 'CASH'::text, 'OTHER'::text])),
  fee_type text DEFAULT 'PERCENTAGE'::text CHECK (fee_type = ANY (ARRAY['PERCENTAGE'::text, 'FIXED'::text])),
  fee_percent numeric DEFAULT 0,
  fee_fixed_amount numeric DEFAULT 0,
  installments_allowed boolean DEFAULT false,
  max_installments integer DEFAULT 1,
  min_installment_value numeric DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_method_fees_pkey PRIMARY KEY (id),
  CONSTRAINT payment_method_fees_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.prescription_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  medication_id uuid,
  medication_name text NOT NULL,
  dosage text NOT NULL,
  frequency text NOT NULL,
  duration text NOT NULL,
  quantity text,
  instructions text,
  CONSTRAINT prescription_items_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_items_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT prescription_items_medication_id_fkey FOREIGN KEY (medication_id) REFERENCES public.medication_library(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  prescription_type text DEFAULT 'MEDICATION'::text CHECK (prescription_type = ANY (ARRAY['MEDICATION'::text, 'EXAM'::text, 'PROCEDURE'::text])),
  diagnosis text,
  notes text,
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'COMPLETED'::text, 'CANCELLED'::text])),
  digital_signature_url text,
  signed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT prescriptions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT prescriptions_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.price_table_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  price_table_id uuid NOT NULL,
  procedure_id uuid NOT NULL,
  price numeric NOT NULL,
  CONSTRAINT price_table_items_pkey PRIMARY KEY (id),
  CONSTRAINT price_table_items_price_table_id_fkey FOREIGN KEY (price_table_id) REFERENCES public.price_tables(id),
  CONSTRAINT price_table_items_procedure_id_fkey FOREIGN KEY (procedure_id) REFERENCES public.procedure(id)
);
CREATE TABLE public.price_tables (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  global_adjustment_percent numeric DEFAULT 0.00,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  type text DEFAULT 'PARTICULAR'::text CHECK (type = ANY (ARRAY['PARTICULAR'::text, 'CONVENIO'::text, 'PARCERIA'::text, 'OUTROS'::text])),
  external_code text,
  contact_phone text,
  notes text,
  CONSTRAINT price_tables_pkey PRIMARY KEY (id),
  CONSTRAINT price_tables_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.procedure (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  base_price numeric NOT NULL,
  duration integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  total_sessions integer NOT NULL DEFAULT 1,
  duration_min integer DEFAULT 30,
  sessions integer DEFAULT 1,
  code_tuss text,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  is_recurring boolean DEFAULT false,
  recurrence_period_days integer,
  recurrence_warning_days integer DEFAULT 20,
  specialty text,
  category text NOT NULL DEFAULT 'CLINICA_GERAL'::text CHECK (category = ANY (ARRAY['CLINICA_GERAL'::text, 'ORTODONTIA'::text, 'HOF'::text])),
  estimated_time_minutes integer DEFAULT 60,
  commission_type text DEFAULT 'PERCENTAGE'::text CHECK (commission_type = ANY (ARRAY['PERCENTAGE'::text, 'FIXED_AMOUNT'::text])),
  commission_base_value numeric DEFAULT 30.00,
  estimated_lab_cost numeric DEFAULT 0,
  CONSTRAINT procedure_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.procedure_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  procedure_id uuid NOT NULL UNIQUE,
  material_cost numeric DEFAULT 0,
  professional_cost numeric DEFAULT 0,
  comission_cost numeric DEFAULT 0,
  operational_overhead numeric DEFAULT 0,
  total_cost numeric DEFAULT ((material_cost + professional_cost) + operational_overhead),
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  tax_percent numeric DEFAULT 0,
  card_fee_percent numeric DEFAULT 0,
  CONSTRAINT procedure_costs_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_costs_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT procedure_costs_procedure_id_fkey FOREIGN KEY (procedure_id) REFERENCES public.procedure(id)
);
CREATE TABLE public.procedure_material_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  treatment_item_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  quantity_used numeric NOT NULL CHECK (quantity_used > 0::numeric),
  unit_cost numeric NOT NULL,
  used_at timestamp with time zone DEFAULT now(),
  used_by uuid,
  CONSTRAINT procedure_material_usage_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_material_usage_treatment_item_id_fkey FOREIGN KEY (treatment_item_id) REFERENCES public.treatment_items(id),
  CONSTRAINT procedure_material_usage_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id),
  CONSTRAINT procedure_material_usage_used_by_fkey FOREIGN KEY (used_by) REFERENCES public.users(id)
);
CREATE TABLE public.procedure_recipe_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipe_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  quantity_needed numeric NOT NULL CHECK (quantity_needed > 0::numeric),
  is_optional boolean DEFAULT false,
  notes text,
  estimated_unit_cost numeric,
  CONSTRAINT procedure_recipe_items_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_recipe_items_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.procedure_recipes(id),
  CONSTRAINT procedure_recipe_items_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id)
);
CREATE TABLE public.procedure_recipes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  procedure_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_default boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT procedure_recipes_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_recipes_procedure_id_fkey FOREIGN KEY (procedure_id) REFERENCES public.procedure(id),
  CONSTRAINT procedure_recipes_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.professional_commissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  professional_id uuid,
  commission_percent numeric DEFAULT 30.00,
  payment_rule text DEFAULT 'ON_RECEIPT'::text CHECK (payment_rule = ANY (ARRAY['ON_RECEIPT'::text, 'ON_EXECUTION'::text])),
  procedure_category text,
  custom_commission_percent numeric,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_commissions_pkey PRIMARY KEY (id),
  CONSTRAINT professional_commissions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT professional_commissions_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.professional_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid,
  month date NOT NULL,
  revenue_goal numeric DEFAULT 0,
  conversion_goal numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_goals_pkey PRIMARY KEY (id),
  CONSTRAINT professional_goals_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.professional_monthly_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  period_month date NOT NULL,
  procedures_completed integer DEFAULT 0,
  total_production_value numeric DEFAULT 0,
  evaluations_performed integer DEFAULT 0,
  budgets_created integer DEFAULT 0,
  budgets_approved integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  total_hours_worked numeric DEFAULT 0,
  average_procedure_duration numeric DEFAULT 0,
  nps_score numeric,
  complaints_count integer DEFAULT 0,
  compliments_count integer DEFAULT 0,
  commission_earned numeric DEFAULT 0,
  average_ticket numeric DEFAULT 0,
  clinic_rank integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_monthly_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT professional_monthly_metrics_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_monthly_metrics_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.professional_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  day_of_week text NOT NULL CHECK (day_of_week = ANY (ARRAY['monday'::text, 'tuesday'::text, 'wednesday'::text, 'thursday'::text, 'friday'::text, 'saturday'::text, 'sunday'::text])),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT professional_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT professional_schedules_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.users(id),
  CONSTRAINT professional_schedules_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.professionals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  crc text UNIQUE,
  specialty text,
  council text,
  is_active boolean DEFAULT true,
  photo_url text,
  color text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professionals_pkey PRIMARY KEY (id),
  CONSTRAINT professionals_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.recurring_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  budget_id uuid,
  contract_type text NOT NULL CHECK (contract_type = ANY (ARRAY['BOTOX_CLUB'::text, 'FILLER_CLUB'::text, 'ORTHO_MAINTENANCE'::text, 'PREVENTION_PLAN'::text, 'AESTHETIC_PLAN'::text, 'OTHER'::text])),
  contract_name text NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date,
  billing_day integer NOT NULL CHECK (billing_day >= 1 AND billing_day <= 31),
  monthly_value numeric NOT NULL CHECK (monthly_value > 0::numeric),
  status text DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'CANCELLED'::text, 'FINISHED'::text])),
  auto_charge boolean DEFAULT false,
  payment_method_id uuid,
  total_charged numeric DEFAULT 0,
  total_paid numeric DEFAULT 0,
  months_active integer DEFAULT 0,
  cancellation_reason text,
  cancellation_date timestamp with time zone,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recurring_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT recurring_contracts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT recurring_contracts_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT recurring_contracts_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT recurring_contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.referral_rewards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  referred_patient_id uuid NOT NULL,
  reward_type text NOT NULL CHECK (reward_type = ANY (ARRAY['CREDIT'::text, 'DISCOUNT'::text, 'GIFT'::text])),
  reward_value numeric NOT NULL DEFAULT 0,
  description text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'REDEEMED'::text, 'EXPIRED'::text, 'CANCELED'::text])),
  earned_date timestamp with time zone DEFAULT now(),
  redeemed_date timestamp with time zone,
  expiry_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_rewards_pkey PRIMARY KEY (id),
  CONSTRAINT referral_rewards_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT referral_rewards_referred_fkey FOREIGN KEY (referred_patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.revenue_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT revenue_category_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_category_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.reward_catalog (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  title text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'legendary'::text])),
  xp_cost integer NOT NULL CHECK (xp_cost > 0),
  role_restriction ARRAY,
  stock_limit integer,
  stock_available integer,
  reward_type text NOT NULL CHECK (reward_type = ANY (ARRAY['voucher'::text, 'time_off'::text, 'bonus'::text, 'recognition'::text, 'team_event'::text, 'experience'::text])),
  monetary_value numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  requires_admin_approval boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT reward_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT reward_catalog_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.reward_redemptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  user_id uuid,
  reward_id uuid,
  xp_spent integer NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'delivered'::text, 'cancelled'::text])),
  approved_by uuid,
  approved_at timestamp without time zone,
  approval_notes text,
  delivered_at timestamp without time zone,
  delivery_notes text,
  cancelled_at timestamp without time zone,
  cancellation_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT reward_redemptions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT reward_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT reward_redemptions_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.reward_catalog(id),
  CONSTRAINT reward_redemptions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.sales_commission_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  user_id uuid NOT NULL,
  commission_type text NOT NULL CHECK (commission_type = ANY (ARRAY['PERCENTAGE'::text, 'FIXED'::text])),
  commission_value numeric NOT NULL CHECK (commission_value >= 0::numeric),
  applies_to_category text,
  min_budget_value numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_commission_rules_pkey PRIMARY KEY (id),
  CONSTRAINT sales_commission_rules_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT sales_commission_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sales_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  period_month date NOT NULL,
  target_revenue numeric DEFAULT 0,
  target_leads integer DEFAULT 0,
  target_conversion_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_goals_pkey PRIMARY KEY (id),
  CONSTRAINT sales_goals_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.sales_scripts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  title text NOT NULL,
  stage text NOT NULL CHECK (stage = ANY (ARRAY['NEW'::text, 'CONTACT'::text, 'BUDGET'::text, 'NEGOTIATION'::text, 'RECOVERY'::text, 'RETENTION'::text])),
  content text NOT NULL,
  tags ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_scripts_pkey PRIMARY KEY (id),
  CONSTRAINT sales_scripts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  cnpj_cpf text,
  contact_name text,
  phone text,
  email text,
  default_expense_category_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT suppliers_default_expense_category_id_fkey FOREIGN KEY (default_expense_category_id) REFERENCES public.expense_category(id)
);
CREATE TABLE public.system_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  user_id uuid,
  user_name text NOT NULL,
  user_email text,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['CREATE'::text, 'UPDATE'::text, 'DELETE'::text, 'LOGIN'::text, 'LOGOUT'::text, 'LOGIN_FAILED'::text, 'EXPORT'::text, 'IMPORT'::text])),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['PATIENT'::text, 'BUDGET'::text, 'APPOINTMENT'::text, 'EXPENSE'::text, 'TRANSACTION'::text, 'CASH_REGISTER'::text, 'USER'::text, 'PROFESSIONAL'::text, 'PROCEDURE'::text, 'LEAD'::text, 'DOCUMENT'::text, 'CLINICAL_NOTE'::text, 'TREATMENT'::text])),
  entity_id uuid,
  entity_name text,
  old_value jsonb,
  new_value jsonb,
  changes_summary text,
  ip_address inet,
  user_agent text,
  session_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT system_audit_logs_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT system_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tactical_operations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['rescue_roi'::text, 'ticket_expansion'::text, 'base_protection'::text, 'milestone_conquest'::text])),
  title text NOT NULL,
  description text,
  financial_impact numeric DEFAULT 0,
  xp_reward integer DEFAULT 0,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'failed'::text, 'expired'::text])),
  related_insight_id uuid,
  related_lead_id uuid,
  related_budget_id uuid,
  related_patient_id uuid,
  deadline timestamp without time zone,
  completed_at timestamp without time zone,
  completed_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  assigned_to uuid,
  mission_type text CHECK (mission_type = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'custom'::text])),
  CONSTRAINT tactical_operations_pkey PRIMARY KEY (id),
  CONSTRAINT tactical_operations_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id),
  CONSTRAINT tactical_operations_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT tactical_operations_related_insight_id_fkey FOREIGN KEY (related_insight_id) REFERENCES public.ai_insights(id),
  CONSTRAINT tactical_operations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  cash_register_id uuid,
  description text NOT NULL,
  amount numeric NOT NULL,
  type USER-DEFINED NOT NULL,
  category text NOT NULL,
  date date NOT NULL,
  payment_method text NOT NULL,
  expense_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT transactions_cash_register_id_fkey FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id),
  CONSTRAINT transactions_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id)
);
CREATE TABLE public.treatment_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  patient_id uuid NOT NULL,
  budget_id uuid NOT NULL,
  procedure_name text NOT NULL,
  region text,
  status USER-DEFINED DEFAULT 'NOT_STARTED'::treatment_status,
  doctor_id uuid,
  execution_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  unit_value numeric DEFAULT 0,
  total_value numeric DEFAULT 0,
  category text NOT NULL CHECK (category = ANY (ARRAY['CLINICA_GERAL'::text, 'ORTODONTIA'::text, 'HOF'::text])),
  specialty text,
  CONSTRAINT treatment_items_pkey PRIMARY KEY (id),
  CONSTRAINT treatment_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT treatment_items_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT treatment_items_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.budgets(id),
  CONSTRAINT treatment_items_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  can_view_financial boolean DEFAULT false,
  can_give_discount boolean DEFAULT false,
  max_discount_percent numeric DEFAULT 0,
  can_delete_transaction boolean DEFAULT false,
  can_close_cash boolean DEFAULT false,
  can_open_cash boolean DEFAULT false,
  can_view_dre boolean DEFAULT false,
  can_create_patient boolean DEFAULT true,
  can_edit_patient boolean DEFAULT true,
  can_delete_patient boolean DEFAULT false,
  can_view_all_patients boolean DEFAULT true,
  can_export_patient_data boolean DEFAULT false,
  can_create_budget boolean DEFAULT true,
  can_approve_budget boolean DEFAULT false,
  can_edit_price boolean DEFAULT false,
  can_delete_budget boolean DEFAULT false,
  can_create_appointment boolean DEFAULT true,
  can_cancel_appointment boolean DEFAULT true,
  can_view_all_schedules boolean DEFAULT true,
  can_edit_others_appointments boolean DEFAULT false,
  can_access_settings boolean DEFAULT false,
  can_manage_users boolean DEFAULT false,
  can_view_audit_logs boolean DEFAULT false,
  can_manage_professionals boolean DEFAULT false,
  can_manage_procedures boolean DEFAULT false,
  can_view_crm boolean DEFAULT true,
  can_convert_lead boolean DEFAULT true,
  can_delete_lead boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_progression (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  clinic_id uuid,
  current_level integer DEFAULT 1 CHECK (current_level >= 1 AND current_level <= 4),
  total_xp integer DEFAULT 0 CHECK (total_xp >= 0),
  clinic_health_score integer DEFAULT 100 CHECK (clinic_health_score >= 0 AND clinic_health_score <= 100),
  health_marketing integer DEFAULT 100,
  health_sales integer DEFAULT 100,
  health_clinical integer DEFAULT 100,
  health_operational integer DEFAULT 100,
  health_financial integer DEFAULT 100,
  current_streak integer DEFAULT 0,
  best_streak integer DEFAULT 0,
  achievements jsonb DEFAULT '[]'::jsonb,
  unlocked_features jsonb DEFAULT '["dashboard_basic"]'::jsonb,
  total_operations_completed integer DEFAULT 0,
  total_revenue_generated numeric DEFAULT 0,
  milestone_50k_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT user_progression_pkey PRIMARY KEY (id),
  CONSTRAINT user_progression_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_progression_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.user_roles_lookup (
  user_id uuid NOT NULL,
  clinic_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  role USER-DEFINED,
  CONSTRAINT user_roles_lookup_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_roles_lookup_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_roles_lookup_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  color text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  phone text,
  professional_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  role USER-DEFINED DEFAULT 'PROFESSIONAL'::role,
  is_active boolean DEFAULT true,
  transaction_pin_hash text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT users_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  name text NOT NULL,
  url text NOT NULL,
  event text NOT NULL CHECK (event = ANY (ARRAY['PATIENT_CREATED'::text, 'APPOINTMENT_CREATED'::text, 'TRANSACTION_CREATED'::text, 'STATUS_CHANGED'::text, 'ALL_EVENTS'::text])),
  secret_key text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  last_triggered_at timestamp with time zone,
  failure_count integer DEFAULT 0,
  CONSTRAINT webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT webhooks_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
